apiVersion: v1
kind: ReplicationController
metadata:
  name: wardle-server
  namespace: wardle
  labels:
    apiserver: "true"
spec:
  replicas: 2
  selector:
    apiserver: "true"
  template:
    metadata:
      labels:
        apiserver: "true"
    spec:
      serviceAccountName: apiserver
      affinity:
        podAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchLabels:
                etcdserver: "true"
      containers:
      - name: wardle-server
        image: mspreitz/kube-sample-apiserver:git-f0d1c65a0e766245a1dcd3c55a42d519bea9cf10
        imagePullPolicy: IfNotPresent
        args:
        - --etcd-servers=http://etcd.wardle.svc.cluster.local:2379
        - -v=5
